jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /microservicio-ingresar
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/autorenting?useSSL=false
      username: sergio
      password: ceiba123
      hikari:
         poolName: pool
